name: build and deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
    
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.dockerhub_username }}
          password: ${{ secrets.dockerhub_password }}
          logout: false
      
      - name: Build and push docker image
        uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: index.docker.io/marwynthedev/openai-demo:${{ github.sha }}
          file: ./Dockerfile

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2.2.5
        with:
          app-name: openaidemo
          publish-profile: ${{ secrets.publish_profile }}
          images: index.docker.io/marwynthedev/openai-demo:${{ github.sha }}
        
